### PR TITLE
Improve Commands.

### PR DESCRIPTION
**Pull request by xism4**

### CODE REVIEW

**Review by sehrschlechtYT — COMMENTED** [review]
Thanks for your pull request.
Does this make a difference to the command output?

**Review by sehrschlechtYT — COMMENTED** [review]
Why shouldn't you be able to use this command in console? Also you don't have to send the message to`Bukkit.getConsoleSender()` as `sender` is the same variable

**Comment by sehrschlechtYT** [comment]
@xIsm4 ?

**Comment by xism4** [comment]
> @xIsm4 ?

Hello, github didn't notificated me sure.

**Comment by xism4** [comment]
> Why shouldn't you be able to use this command in console? Also you don't have to send the message to`Bukkit.getConsoleSender()` as `sender` is the same variable

Also why u should use it on console? Can create conflicts.

**Comment by sehrschlechtYT** [comment]
> > Why shouldn't you be able to use this command in console? Also you don't have to send the message to`Bukkit.getConsoleSender()` as `sender` is the same variable
> 
> Also why u should use it on console? Can create conflicts.

It can't create conflicts as I don't cast the sender to a Player.

**Comment by sehrschlechtYT** [comment]
@xIsm4

**Pull request closed without merging**
